// CRATE `traits` =============================================================
use std::marker::PhantomData;
use std::num::NonZeroU32;
use std::ops::{Deref, DerefMut};

/// Assigned by `Allocator::alloc`. Deliberately small and opaque: it does
/// *not* hold a reference to any `Backend`, so it can't free itself in
/// `Drop` -- see the README's "Freeing" section for why that's fine (the
/// generated `Guard` wrapper types are responsible for freeing the
/// `UniquePointer`s they own).
///
/// `index` is a stable identity assigned once by `Allocator` and never
/// changes for the lifetime of this pointer -- even though the region it
/// (eventually) refers to may move around on disk during compaction, and
/// even though this pointer may not have been flushed to the snapshot yet
/// at all. `Allocator` resolves `index` to the pointer's current
/// `position` (where it's serialized in the snapshot, once flushed) and
/// `target` (where the pointed-to region currently sits, once its own
/// allocation is flushed); both start out `None` and become `Some` the
/// first time a flush touches them.
///
/// Variance: `PhantomData<*const T>` rather than plain `PhantomData<T>`.
/// Both give covariance in `T`, which is sound here -- mutation only ever
/// happens through a `Guard` requiring exclusive access, never through a
/// shared reference the way `Cell<T>`'s interior mutability does, so the
/// aliasing+mutation+covariance combination that forces `Cell<T>` to be
/// invariant doesn't apply. `*const T` is preferred over plain `T` because
/// `UniquePointer` never actually runs `T`'s destructor (freeing just
/// discards a byte range), so it shouldn't impose `PhantomData<T>`'s
/// "may drop a T" (drop-check) obligation.
pub struct UniquePointer<T> {
    index: NonZeroU32,
    _marker: PhantomData<*const T>,
}

/// Records operations to the journal. Appending may itself require
/// allocation (growing the journal's own storage, or a single oversized
/// `Op`) -- which is the reason `Journal` and `Allocator` are kept as two
/// traits unified by one `Backend` bound, rather than two independent type
/// parameters: a `Journal` implementation will generally need the same
/// `Allocator` the rest of the system uses, so splitting them into
/// separately-mixable type parameters wouldn't actually decouple them.
pub trait Journal {
    fn record<T: Persistable>(&self, op: &T::Op<'_>);
}

/// Allocates and frees regions in the backed heap, and resolves
/// `UniquePointer`s to their current `(position, target)`. The concrete
/// registry (index-keyed table + position-ordered range-query structure,
/// see README) is intentionally not sketched here yet -- see "mock
/// `Allocator`" under the README's Open Questions.
pub trait Allocator {
    fn free<T: Persistable>(&self, pointer: UniquePointer<T>);
}

/// The bound every `Persistable`/`Guard` is generic over. A blanket impl
/// means concrete backend types only ever need to implement `Journal` and
/// `Allocator` separately; application code names `Backend`, not the two
/// halves.
pub trait Backend: Journal + Allocator {}
impl<B: Journal + Allocator> Backend for B {}

/// A plain, in-memory value type that *could* be persisted -- it has the
/// right shape (an `Op` log, a paired `Guard` view) -- but isn't yet tied
/// to any backend. Only ever accessed read-only; see `Guard` for mutation.
pub trait Persistable {
    /// Lifetime-parameterized so that, e.g., `Vec::push` can record a
    /// *reference* to the value it just pushed (see `VecGuard::push`
    /// below) instead of needing to clone it or move it twice. This is
    /// more machinery than a plain (non-generic-associated) `type Op`
    /// would need -- flagged explicitly as a real complexity cost, not a
    /// mechanical fix, since it propagates into `Journal::record` too.
    type Op<'a>: 'a
    where
        Self: 'a;

    type Guard<'s, B: Backend>: Guard;

    /// Borrows both `self` and a `Backend` for `'s`, producing a `Guard`
    /// through which mutations are recorded and applied.
    fn guard<'s, B: Backend>(&'s mut self, backend: &'s B) -> Self::Guard<'s, B>;
}

/// A live, mutation-capable, RAII-style view onto a `Persistable` value,
/// tied to a `Backend` for its lifetime -- the write-side counterpart of
/// `Persistable`, in the same relationship `MutexGuard` has to `Mutex`.
/// Rarely implemented manually; usually generated by `#[derive(Persistable)]`.
pub trait Guard {
    type Persistable: Persistable;
    type Backend: Backend;

    fn as_persistable(&self) -> &Self::Persistable;
    fn as_persistable_mut(&mut self) -> &mut Self::Persistable;
    fn backend(&self) -> &Self::Backend;
}

// Note: there is deliberately no blanket `impl<T: Guard> Deref for T`
// here. `Guard` is a foreign trait from the point of view of any
// downstream crate, so `Self` in a blanket impl over it would be a fully
// generic, uncovered type parameter -- exactly what Rust's orphan rules
// forbid (E0210), regardless of the trait bound on it. Instead, each
// concrete guard type (e.g. `VecGuard` below) gets its own `Deref`/
// `DerefMut` impl generated alongside it, since those are local types in
// whatever crate the macro expands in.

// CRATE `types` ==============================================================

/// Naming convention: a `Persistable` named `Foo` gets a generated guard
/// type named `FooGuard`.
#[derive(Persistable(op = VecOp, guard = VecGuard))]
pub struct Vec<T> {
    data: std::vec::Vec<T>,
}

pub enum VecOp<'a, T> {
    Push(&'a T),
}

impl<T> Vec<T> {
    pub fn new() -> Self {
        Vec {
            data: std::vec::Vec::new(),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }
}

impl<'s, T: Persistable, B: Backend> VecGuard<'s, T, B> {
    pub fn push(&mut self, value: T) {
        // Push first, then record a *reference* to the now-last element,
        // rather than moving `value` into the `Op` and into `self.inner`
        // both (which doesn't compile -- `T` isn't `Copy`) or cloning it
        // (which would need an unnecessary `T: Clone` bound). `.data` here
        // is `Vec<T>`'s own private field -- accessible because this impl
        // block is generated into the same module as `struct Vec<T>`.
        self.inner.data.push(value);
        let last = &self.inner.data[self.inner.data.len() - 1];
        self.backend.record::<Vec<T>>(&VecOp::Push(last));
    }

    pub fn get_mut(&mut self, index: usize) -> Option<T::Guard<'_, B>> {
        self.inner
            .data
            .get_mut(index)
            .map(|item| item.guard(self.backend))
    }
}

// MACRO-GENERATED CODE IN CRATE `types` ======================================

/// Generated from `#[derive(Persistable)]` on `struct Vec<T>`.
impl<T> Persistable for Vec<T> {
    type Op<'a>
        = VecOp<'a, T>
    where
        Self: 'a;
    type Guard<'s, B: Backend> = VecGuard<'s, T, B>;

    fn guard<'s, B: Backend>(&'s mut self, backend: &'s B) -> Self::Guard<'s, B> {
        VecGuard {
            inner: self,
            backend,
        }
    }
}

/// Generated from `#[derive(Persistable)]` on `struct Vec<T>`.
/// `inner` borrows the real `Vec<T>` (the `Persistable` wrapper, not its
/// private `std::vec::Vec` field directly) for `'s`, so that
/// `as_persistable`/`Deref` below have something to return a reference to.
/// `backend` is a plain (non-owning, non-refcounted) reference, stored
/// once here and reborrowed down into nested guards (see `get_mut` above)
/// rather than re-supplied by the caller at each call.
pub struct VecGuard<'s, T, B = DefaultBackend> {
    inner: &'s mut Vec<T>,
    backend: &'s B,
}

/// Generated from `#[derive(Persistable)]` on `struct Vec<T>`.
impl<'s, T, B: Backend> Guard for VecGuard<'s, T, B> {
    type Persistable = Vec<T>;
    type Backend = B;

    fn as_persistable(&self) -> &Self::Persistable {
        self.inner
    }

    fn as_persistable_mut(&mut self) -> &mut Self::Persistable {
        self.inner
    }

    fn backend(&self) -> &Self::Backend {
        self.backend
    }
}

/// Generated from `#[derive(Persistable)]` on `struct Vec<T>`.
impl<'s, T, B> Deref for VecGuard<'s, T, B> {
    type Target = Vec<T>;

    fn deref(&self) -> &Self::Target {
        self.inner
    }
}

/// Generated from `#[derive(Persistable)]` on `struct Vec<T>`.
impl<'s, T, B> DerefMut for VecGuard<'s, T, B> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.inner
    }
}
