// NOTE: I'm not happy with the names `Backable`, `Backed`, and `Sink`. I think
// the first two are grammatically confusing, and `Sink` no longer necessarily
// makes sense if it also has a `free` method, i.e., also encompasses the
// memory allocator. Come up with better names and change them throughout the
// codebase.

// CRATE `traits` =============================================================
use std::ops::{Deref, DerefMut};

trait Sink {
    fn record<T: Backable>(&self, op: &T::Op);
    fn free<T: Backable>(&self, pointer: OwnedPointer<T>);
}

trait Backable {
    type Op;
    type Backed<S: Sink>: Backed;

    fn back<S: Sink>(&mut self, sink: &S) -> Self::Backed<'_, S>;
}

/// Rarely implemented manually, usually generated by the `#[backed]` attribute.
trait Backed {
    type Backable: Backable;
    type Sink: Sink;

    fn as_backable(&self) -> &Self::Backable;
    fn as_backable_mut(&mut self) -> &mut Self::Backable;
    fn sink(&self) -> &Self::Sink;
}

impl<T: Backed> Deref for T {
    type Target = T::Backable;

    fn deref(&self) -> &Self::Target {
        self.as_backable()
    }
}

impl<T: Backed> DerefMut for T {
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.as_backable_mut()
    }
}

// CRATE `types` ==============================================================

#[derive(Backable(op=VecOp, mut=VecMut))]
struct Vec<T> {
    data: std::Vec<T>,
}

enum VecOp<T> {
    Push(T),
}

impl<T> Vec<T> {
    pub fn new() -> Self {
        Vec {
            data: std::Vec::new(),
        }
    }

    pub fn len(&self) -> usize {
        self.data.len()
    }
}

impl<'s, T: Backable, S: Sink> VecMut<'s, T, S> {
    pub fn push(&mut self, value: T) {
        self.sink.record(&VecOp::Push(value));
        self.data.push(value);
    }

    pub fn get_mut(&mut self, sink: &mut impl Sink, index: usize) -> Option<&mut T::Backed<S>> {
        self.data.get_mut(index).map(|item| item.back(sink))
    }
}

// MACRO-GENERATED CODE IN CRATE `types` ======================================

/// Generated from #[derive(Backable)] on `struct Vec<T>`.
impl<T> Backable for Vec<T> {
    type Op = VecOp<T>;
    type Backed<'s, S: Sink> = VecMut<'s, T, S>;

    fn back<S: Sink>(&mut self, sink: &S) -> Self::Backed<'_, S> {
        VecMut { data: self, sink }
    }
}

/// Generated from #[derive(Backable)] on `struct Vec<T>`.
struct VecMut<'s, T, S = DefaultSink> {
    data: Vec<T>,
    sink: &'s S,
}

/// Generated from #[derive(Backable)] on `struct Vec<T>`.
impl<'s, T, S: Sink> Backed for VecMut<'s, T, S> {
    type Backable = Vec<T>;
    type Sink = S;

    fn as_backable(&self) -> &Self::Backable {
        &self.data
    }

    fn as_backable_mut(&mut self) -> &mut Self::Backable {
        &mut self.data
    }

    fn sink(&self) -> &Self::Sink {
        &self.sink
    }
}
