//! [`Guard`]: the mutation-capable view onto a [`Persistable`](crate::Persistable)
//! value, tied to a [`WriteBackend`] for its lifetime.
//!
//! The write-side counterpart of `Persistable`, in the same relationship
//! `MutexGuard` has to `Mutex`. A guard holds `&'s B` (not `&'s mut B`), which is
//! what lets a parent guard hand the *same* backend reference to each of its
//! field guards by reborrow -- see `kladde-heap`'s `backend` module docs for why
//! the write half is `&self` and the read half is `&mut self`.
//!
//! Rarely implemented by hand; usually generated by `#[derive(Persistable)]`.

use kladde_heap::WriteBackend;

/// A live, mutation-capable, RAII-style view onto a persistable value.
///
/// `Persistable` is deliberately **not** a bound on
/// [`Persistable`](Guard::Persistable): the trait is generic over the pointer
/// type, so a bound here would have to name a pointer type this trait has no
/// reason to know. The association is pinned anyway by
/// [`Persistable::Guard`](crate::Persistable::Guard)'s own
/// `Guard<Persistable = Self, Backend = B>` constraint.
pub trait Guard {
    /// The value this guard mutates.
    type Persistable;
    /// The backend the mutations are recorded against.
    type Backend: WriteBackend;

    fn as_persistable(&self) -> &Self::Persistable;
    fn as_persistable_mut(&mut self) -> &mut Self::Persistable;
    fn backend(&self) -> &Self::Backend;
}

// Note: there is deliberately no blanket `impl<T: Guard> Deref for T` here.
// `Guard` is a foreign trait from the point of view of any downstream crate, so
// `Self` in a blanket impl over it would be a fully generic, uncovered type
// parameter -- exactly what Rust's orphan rules forbid (E0210), regardless of
// the trait bound on it. Instead, each concrete guard type gets its own
// `Deref`/`DerefMut` impl generated alongside it, since those are local types in
// whatever crate the macro (or hand-written container) expands in.
