//! [`Guard`]: the mutation-capable view onto a [`Persistable`](crate::Persistable)
//! value, tied to a [`WriteBackend`] for its lifetime.
//!
//! The write-side counterpart of `Persistable`, in the same relationship
//! `MutexGuard` has to `Mutex`. A guard holds `&'s B` (not `&'s mut B`), which
//! is what lets a parent guard hand the *same* backend reference to each of its
//! field guards by reborrow.
//!
//! Rarely implemented by hand; usually generated by `#[derive(Persistable)]`.

use kladde_store::WriteBackend;

/// A live, mutation-capable, RAII-style view onto a persistable value.
///
/// Every mutating method of a guard records the change in the backend's
/// journal and then mutates the in-memory value, in that order, and returns a
/// `Result`: a failed recording leaves the value as it was. Guards also
/// dereference to the value, so read-only methods stay available.
///
/// `Persistable` is deliberately **not** a bound on
/// [`Persistable`](Guard::Persistable): the trait is generic over the pointer
/// type, so a bound here would have to name a pointer type this trait has no
/// reason to know. The association is pinned anyway by
/// [`Persistable::Guard`](crate::Persistable::Guard)'s own
/// `Guard<Persistable = Self, Backend = B>` constraint.
///
/// ```
/// use kladde_persist::{Guard, Location, Persistable};
/// use kladde_store::{MemoryStorage, Store, WriteBackend};
///
/// let store = Store::create(Box::new(MemoryStorage::new()), Default::default())?;
/// let p = store.alloc(1)?;
/// let mut flag = false;
/// let mut guard = flag.guard(&store, Location::new(p.raw(), 0));
/// guard.set(true)?;
/// assert!(*guard.as_persistable());
/// # Ok::<(), kladde_store::Error>(())
/// ```
pub trait Guard {
    /// The value this guard mutates.
    type Persistable;
    /// The backend the mutations are recorded in.
    type Backend: WriteBackend;

    /// The value, for reading.
    fn as_persistable(&self) -> &Self::Persistable;
    /// The value, for mutating in memory only. What is changed through this
    /// reference is not recorded, so it must not change anything the value
    /// persists.
    fn as_persistable_mut(&mut self) -> &mut Self::Persistable;
    /// The backend the guard records in.
    fn backend(&self) -> &Self::Backend;
}

// Note: there is deliberately no blanket `impl<T: Guard> Deref for T` here.
// `Guard` is a foreign trait from the point of view of any downstream crate, so
// `Self` in a blanket impl over it would be a fully generic, uncovered type
// parameter -- exactly what Rust's orphan rules forbid (E0210), regardless of
// the trait bound on it. Instead, each concrete guard type gets its own
// `Deref`/`DerefMut` impl generated alongside it, since those are local types in
// whatever crate the macro (or hand-written container) expands in.
