//! The crate application code actually depends on: opening/creating a
//! [`Kladde`] root value, and the [`DefaultBackend`] that backs it.
//!
//! ## What changed when kladde moved onto `kladde-heap`
//!
//! v1's `DefaultBackend` was a hand-rolled `Vec<Microop>` journal replayed
//! against an in-memory `MockAllocator` (the former `kladde-alloc` crate), with
//! no address space at all -- every allocation was its own `Box<[u8]>`. It is
//! now a [`kladde_heap`] backend: a real address space with placement, gaps,
//! and incremental compaction, over a `Storage` byte interface.
//!
//! Two consequences for application code:
//!
//! - **Mutations are visible immediately.** [`DefaultBackend`] is *unjournaled*
//!   -- it applies every operation as it happens -- so a [`Kladde::load`] no
//!   longer has to be preceded by a flush. (The journaled backend
//!   `kladde_heap::JournaledWriteBackend` exists, but plugging it in is blocked
//!   on deciding what a flush *means*: a durability commit or a memory-bounding
//!   checkpoint. `Kladde` is generic over its backend so that swap needs no
//!   change here.)
//! - **[`Kladde::flush`] now means "compact"**, not "materialize". See its doc
//!   comment.
//!
//! There is still no real file behind any of this: `DefaultBackend`'s storage is
//! in memory, so state lives only as long as the process does. That is why there
//! is no `open`/`create` taking a `Path` yet.

// Everything else this crate needs is in scope via the `pub use` below.
use kladde_persist::CompactingBackend;

/// The derive macro, re-exported so an application needs only this crate.
///
/// Named the same as the [`Persistable`] trait, which is legal and deliberate --
/// they live in different namespaces, exactly as `serde`'s `Serialize` does.
#[cfg(feature = "derive")]
pub use kladde_derive::Persistable;

// Everything a `Persistable` impl -- derived or hand-written -- has to name.
//
// The point is that an application depends on `kladde` alone. Code generated by
// `#[derive(Persistable)]` is rooted at `::kladde`, and an author who later
// hand-writes an impl finds the same items here, so no second dependency is ever
// added and there is no way to end up with two incompatible versions of the same
// trait. A library built on `kladde-persist` without this facade names them
// there instead, and tells the macro so with `#[kladde(crate = "kladde_persist")]`.
pub use kladde_persist::{
    Backend, BackendError, Guard, Location, Persistable, Pointer, PointerRepr, ReadBackend,
    UniquePointer, UniquePointerFixedSize, UniquePointerResizable, Word, WriteBackend,
    WriteBackendExt,
};

// The schema/fingerprint surface, so an application can inspect its root type's
// schema (`T::schema()`/`T::fingerprint()`) without naming `kladde-schema`.
pub use kladde_persist::{
    Field, Fingerprint, SchemaBuilder, TypeDescriptor, TypeRef, TypeTable, Variant, Version,
};

pub use kladde_heap::CompactionProgress;

/// The concrete backend a [`Kladde`] uses unless told otherwise: an in-memory
/// [`kladde_heap`] backend with `Pointer = Pointer<u32>` and `Size = u32`,
/// applying every operation immediately and compacting on demand.
///
/// A type alias rather than a newtype, so an application that outgrows it can
/// name any other `kladde-heap` backend in [`Kladde`]'s second parameter without
/// this crate mediating.
pub type DefaultBackend = kladde_heap::MockBackend;

/// How many bytes of copying [`Kladde::flush`] will spend per call.
pub const DEFAULT_COMPACTION_BUDGET: usize = kladde_heap::DEFAULT_COMPACTION_BUDGET;

/// A root [`Persistable`] value paired with its backend -- the entry point
/// application code actually uses.
///
/// Unlike every other `Persistable` value, the root gets its own allocation
/// *eagerly*, in [`Kladde::new`] -- it doesn't have the "constructed without a
/// backend in hand" problem that makes every other container's pointer lazy,
/// since `root` and `backend` are brought together in the same call. See
/// `spec.md`'s "Pointers and Memory Management".
///
/// `B` is the backend. It defaults to [`DefaultBackend`]; the parameter exists
/// so a journaled or file-backed backend can be substituted without changing any
/// of this type's code.
pub struct Kladde<T, B: Backend = DefaultBackend> {
    root: T,
    backend: B,
    root_pointer: UniquePointer<T, B::Pointer>,
}

impl<T: Persistable> Kladde<T, DefaultBackend> {
    /// Wraps `root` with a fresh, empty [`DefaultBackend`], allocating the
    /// root's own storage immediately.
    ///
    /// Deliberately fixed to `DefaultBackend` rather than generic over `B:
    /// Default`: a bare `Kladde::new(value)` has nothing to infer the backend
    /// from (a type parameter's default does not participate in inference), so a
    /// generic `new` would force every call site to annotate. Use
    /// [`with_backend`](Kladde::with_backend) for any other backend.
    pub fn new(root: T) -> Self {
        Self::with_backend(root, DefaultBackend::default())
    }
}

impl<T, B> Kladde<T, B>
where
    T: Persistable<B::Pointer>,
    B: WriteBackend,
{
    /// Wraps `root` with `backend`, allocating the root's own storage
    /// immediately.
    pub fn with_backend(root: T, backend: B) -> Self {
        let root_pointer = backend.alloc_typed::<T>();
        Kladde {
            root,
            backend,
            root_pointer,
        }
    }

    /// Read-only access to the root value.
    pub fn get(&self) -> &T {
        &self.root
    }

    /// A [`Guard`](kladde_persist::Guard) through which mutations to the root
    /// value are recorded and applied.
    pub fn guard(&mut self) -> <T as Persistable<B::Pointer>>::Guard<'_, B> {
        let location = Location::new(self.root_pointer.raw(), Word::zero());
        self.root.guard(&self.backend, location)
    }

    pub fn backend(&self) -> &B {
        &self.backend
    }
}

impl<T, B> Kladde<T, B>
where
    T: Persistable<B::Pointer>,
    B: ReadBackend,
{
    /// Reconstructs a fresh `T` purely from the backend's storage -- no
    /// reference to `self.root`. The primary correctness test for the write
    /// path: this should always equal `self.root`.
    ///
    /// Takes `&mut self` because reads are sequential and hand out a real
    /// seekable cursor. A useful side effect: the borrow checker forbids loading
    /// while any guard (which holds `&self`) is still alive.
    pub fn load(&mut self) -> T {
        let location = Location::new(self.root_pointer.raw(), Word::zero());
        T::load(&mut self.backend, location)
    }
}

impl<T, B> Kladde<T, B>
where
    T: Persistable<B::Pointer>,
    B: CompactingBackend,
{
    /// Spends a bounded amount of work squeezing fragmentation out of the
    /// backing store, then truncates it.
    ///
    /// **This is not v1's `flush`.** Under [`DefaultBackend`] every mutation is
    /// already applied by the time the guard method returns, so there is nothing
    /// buffered to materialize; what a periodic call still buys is compaction.
    /// The name is kept because this is the seam a journaled backend's real
    /// flush will attach to -- see the crate docs.
    pub fn flush(&mut self) -> CompactionProgress {
        self.compact(DEFAULT_COMPACTION_BUDGET)
    }

    /// [`flush`](Self::flush) with an explicit byte budget.
    pub fn compact(&mut self, budget: usize) -> CompactionProgress {
        self.backend.compact_incrementally(budget)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use kladde_persist::{Guard, PointerRepr, Word};
    use std::io::Read;

    struct Counter(u32);

    impl<P: PointerRepr> Persistable<P> for Counter {
        const INLINE_SIZE: usize = 4;

        type Guard<'s, B: WriteBackend<Pointer = P>>
            = CounterGuard<'s, B>
        where
            Self: 's,
            B: 's;

        fn guard<'s, B: WriteBackend<Pointer = P>>(
            &'s mut self,
            backend: &'s B,
            location: Location<P, B::Size>,
        ) -> Self::Guard<'s, B> {
            CounterGuard {
                inner: self,
                backend,
                location,
            }
        }

        fn store<B: WriteBackend<Pointer = P>>(
            &mut self,
            backend: &B,
            location: Location<P, B::Size>,
        ) {
            backend.write(location.anchor, location.offset, &self.0.to_le_bytes());
        }

        fn load<B: ReadBackend<Pointer = P>>(
            backend: &mut B,
            location: Location<P, B::Size>,
        ) -> Self {
            let mut bytes = [0u8; 4];
            backend
                .read_at(location.anchor, location.offset)
                .read_exact(&mut bytes)
                .expect("read Counter");
            Counter(u32::from_le_bytes(bytes))
        }

        fn describe_local(
            _builder: &mut kladde_persist::SchemaBuilder,
        ) -> kladde_persist::TypeDescriptor {
            kladde_persist::TypeDescriptor::Primitive(kladde_persist::Primitive::U32)
        }
    }

    struct CounterGuard<'s, B: WriteBackend> {
        inner: &'s mut Counter,
        backend: &'s B,
        location: Location<B::Pointer, B::Size>,
    }

    impl<'s, B: WriteBackend> CounterGuard<'s, B> {
        fn set(&mut self, value: u32) {
            self.backend.write(
                self.location.anchor,
                self.location.offset,
                &value.to_le_bytes(),
            );
            self.inner.0 = value;
        }
    }

    impl<'s, B: WriteBackend> Guard for CounterGuard<'s, B> {
        type Persistable = Counter;
        type Backend = B;

        fn as_persistable(&self) -> &Counter {
            self.inner
        }
        fn as_persistable_mut(&mut self) -> &mut Counter {
            self.inner
        }
        fn backend(&self) -> &B {
            self.backend
        }
    }

    #[test]
    fn mutation_updates_state_and_is_immediately_readable() {
        let mut kladde = Kladde::new(Counter(0));

        kladde.guard().set(42);

        assert_eq!(kladde.get().0, 42);
        // No flush needed: the default backend is unjournaled, so `load` sees
        // the mutation right away. This is the behavior change from v1's
        // journal-and-replay `DefaultBackend`.
        assert_eq!(kladde.load().0, 42);
    }

    #[test]
    fn flushing_compacts_and_leaves_the_value_intact() {
        let mut kladde = Kladde::new(Counter(0));
        kladde.guard().set(7);

        let progress = kladde.flush();

        assert!(
            progress.quiesced,
            "a single-allocation heap is already compact"
        );
        assert_eq!(kladde.load().0, 7);
    }

    #[test]
    fn the_root_allocation_is_created_eagerly() {
        let kladde = Kladde::new(Counter(0));
        assert_eq!(kladde.backend().live_count(), 1);
    }

    #[test]
    fn allocations_round_trip_through_the_backend_without_a_flush() {
        let backend = DefaultBackend::new();

        let pointer = backend.alloc_resizable_array::<u8>(16);
        assert_eq!(
            Backend::size(&backend, pointer.raw()).unwrap(),
            16,
            "size is readable immediately -- nothing is deferred"
        );

        backend.resize(&pointer, 40).unwrap();
        assert_eq!(Backend::size(&backend, pointer.raw()).unwrap(), 40);

        let live = backend.live_count();
        backend.free_resizable(pointer);
        assert_eq!(backend.live_count(), live - 1);
    }

    #[test]
    fn splice_replaces_a_range_and_resizes_in_one_call() {
        let mut backend = DefaultBackend::new();
        let pointer = backend.alloc_resizable_array::<u8>(4);
        backend.write(pointer.raw(), 0, &[1, 2, 3, 4]);

        backend.splice(&pointer, 1, 2, &[9, 9, 9]);

        assert_eq!(Backend::size(&backend, pointer.raw()).unwrap(), 5);
        let mut bytes = [0u8; 5];
        backend
            .read_at(pointer.raw(), Word::zero())
            .read_exact(&mut bytes)
            .unwrap();
        assert_eq!(bytes, [1, 9, 9, 9, 4]);
    }
}
