//! Durable data structures: plain Rust values whose every mutation is
//! recorded durably as it happens.
//!
//! A [`Kladde<T>`] pairs a root value with the file that backs it. Reading is
//! ordinary reading, through [`get`](Kladde::get). Mutating goes through
//! [`guard`](Kladde::guard), whose methods append the change to the file's
//! journal before they return, so there is no save call.
//!
//! ```
//! use kladde::{Kladde, Persistable};
//! use kladde_types::{PersistableString, PersistableVec};
//!
//! #[derive(Persistable)]
//! struct Notes {
//!     title: PersistableString,
//!     lines: PersistableVec<PersistableString>,
//! }
//!
//! let mut notes = Kladde::new(Notes {
//!     title: PersistableString::from("today"),
//!     lines: PersistableVec::new(),
//! });
//! notes.guard().lines_mut().push(PersistableString::from("wrote a doc"))?;
//! assert_eq!(notes.get().lines.len(), 1);
//! # Ok::<(), kladde::Error>(())
//! ```
//!
//! This crate re-exports everything a `Persistable` implementation names,
//! derived or hand-written, so an application depends on it and on the
//! containers of `kladde-types`, and on nothing below.

use std::path::Path;

/// The derive macro, re-exported so an application needs only this crate.
///
/// Named the same as the [`Persistable`] trait, which is legal and deliberate:
/// they live in different namespaces, exactly as `serde`'s `Serialize` does.
#[cfg(feature = "derive")]
pub use kladde_derive::Persistable;

// Everything a `Persistable` impl -- derived or hand-written -- names. Code
// generated by `#[derive(Persistable)]` is rooted at `::kladde`, and an author
// who hand-writes an impl finds the same items here, so there is never a second
// dependency, and never two incompatible copies of the same trait.
pub use kladde_persist::{
    decode_option, decode_option_slice, encode_option, enum_packed_size, enum_slotted_size,
    read_allocation, replace, slot_size, splice_at, sum_sizes, varint_len, write_encoded,
    write_varint, Backend, BoolGuard, CharGuard, Encoding, Error, F32Guard, F64Guard, FieldOffsets,
    Guard, I16Guard, I32Guard, I64Guard, I8Guard, Input, Link, Location, Node, Packed, Persistable,
    Place, Pointer, PointerRepr, ReadBackend, Result, SchemaBuilder, Slotted, TupleGuard, U16Guard,
    U32Guard, U64Guard, U8Guard, UniquePointer, Word, WriteBackend,
};

// The schema and fingerprint surface, so an application can inspect its root
// type's schema without naming `kladde-schema`.
pub use kladde_persist::{
    Field, Fingerprint, Primitive, TypeDescriptor, TypeRef, TypeTable, Variant, Version,
};

// The storage layer's application-facing items: the backend guards run
// against, how it is tuned, what it reports, and where its bytes live.
pub use kladde_store::{FileStorage, MemoryStorage, Options, Stats, Storage, Store};

/// The guard of a root value of type `T`, as [`Kladde::guard`] hands it out.
///
/// ```
/// use kladde::{Kladde, RootGuard};
///
/// fn bump(mut guard: RootGuard<'_, u32>) -> kladde::Result<()> {
///     let next = *guard + 1;
///     guard.set(next)
/// }
/// let mut k = Kladde::new(1u32);
/// bump(k.guard())?;
/// assert_eq!(*k.get(), 2);
/// # Ok::<(), kladde::Error>(())
/// ```
pub type RootGuard<'a, T> = <T as Persistable>::Guard<'a, Store, Slotted>;

/// A root [`Persistable`] value paired with the file that backs it.
///
/// Everything reachable from the root is backed. Reads go through
/// [`get`](Self::get) and cost what reading the plain value costs; mutations
/// go through [`guard`](Self::guard), and each one is in the file's journal
/// once it returns `Ok`. The file is brought up to date with the journal by
/// flushes, which happen by themselves as the journal grows, and on
/// [`flush`](Self::flush) and [`close`](Self::close).
///
/// ```
/// use kladde::Kladde;
/// use kladde_types::PersistableVec;
///
/// let path = std::env::temp_dir().join("kladde-doc-kladde.kladde");
/// let mut v = Kladde::create(&path, PersistableVec::<u32>::new())?;
/// v.guard().push(1)?;
/// v.close()?;
/// let v = Kladde::<PersistableVec<u32>>::open(&path)?;
/// assert_eq!(v.get().as_slice(), &[1]);
/// # std::fs::remove_file(&path).ok();
/// # Ok::<(), kladde::Error>(())
/// ```
pub struct Kladde<T: Persistable + 'static> {
    store: Store,
    root: T,
    root_pointer: Pointer,
}

impl<T: Persistable + 'static> Kladde<T> {
    /// Wraps `root` in a file that lives in memory: the same behaviour as a
    /// file on disk, for tests and for trying things out.
    ///
    /// ```
    /// use kladde::Kladde;
    ///
    /// let mut n = Kladde::new(0u64);
    /// n.guard().set(5)?;
    /// assert_eq!(*n.get(), 5);
    /// # Ok::<(), kladde::Error>(())
    /// ```
    pub fn new(root: T) -> Self {
        Self::create_in(Box::new(MemoryStorage::new()), root, Options::default())
            .expect("a file in memory cannot fail")
    }

    /// Creates the file at `path`, replacing any file there, holding `root`.
    ///
    /// The file records `T`'s schema and fingerprint, and is durable when this
    /// returns. See [`Kladde`] for an example.
    pub fn create(path: impl AsRef<Path>, root: T) -> Result<Self> {
        let storage = FileStorage::create(path.as_ref())?;
        Self::create_in(Box::new(storage), root, Options::default())
    }

    /// Creates a kladde file holding `root` in `storage`, discarding whatever
    /// it held, with `opts` tuning the store.
    ///
    /// ```
    /// use kladde::{Kladde, MemoryStorage, Options};
    ///
    /// let opts = Options { journal_budget_pages: 8, ..Default::default() };
    /// let k = Kladde::create_in(Box::new(MemoryStorage::new()), 7u8, opts)?;
    /// assert_eq!(*k.get(), 7);
    /// # Ok::<(), kladde::Error>(())
    /// ```
    pub fn create_in(storage: Box<dyn Storage>, mut root: T, opts: Options) -> Result<Self> {
        let store = Store::create(storage, opts)?;
        let table = T::schema().encode();
        let fingerprint = *T::fingerprint().as_bytes();
        let root_pointer = store.atomically(|| {
            let pointer = store.alloc(size(slot_size::<T, Pointer>())?)?;
            let schema = store.alloc(size(table.len())?)?;
            store.write(schema.raw(), 0, &table)?;
            root.store::<_, Slotted>(&store, Location::new(pointer.raw(), 0))?;
            store.set_roots(pointer.raw(), schema.raw(), fingerprint);
            Ok(pointer.raw())
        })?;
        store.flush()?;
        Ok(Kladde {
            store,
            root,
            root_pointer,
        })
    }

    /// Opens the file at `path` and loads its root value.
    ///
    /// Recovers every mutation that returned `Ok` before the process that
    /// wrote them died, whether or not a flush folded it. Fails with
    /// [`Error::SchemaMismatch`] if the file's root type is not `T`, as its
    /// fingerprint tells. See [`Kladde`] for an example.
    pub fn open(path: impl AsRef<Path>) -> Result<Self> {
        let storage = FileStorage::open(path.as_ref())?;
        Self::open_in(Box::new(storage), Options::default())
    }

    /// Opens the kladde file in `storage`, with `opts` tuning the store.
    ///
    /// ```
    /// use kladde::{Kladde, MemoryStorage, Options};
    ///
    /// let storage = MemoryStorage::new();
    /// let k = Kladde::create_in(Box::new(storage.clone()), 3u16, Options::default())?;
    /// drop(k);
    /// let k = Kladde::<u16>::open_in(Box::new(storage), Options::default())?;
    /// assert_eq!(*k.get(), 3);
    /// // The fingerprint check refuses the wrong root type.
    /// # let storage = MemoryStorage::new();
    /// # drop(Kladde::create_in(Box::new(storage.clone()), 3u16, Options::default())?);
    /// assert!(Kladde::<u32>::open_in(Box::new(storage), Options::default()).is_err());
    /// # Ok::<(), kladde::Error>(())
    /// ```
    pub fn open_in(storage: Box<dyn Storage>, opts: Options) -> Result<Self> {
        let mut store = Store::open(storage, opts)?;
        let root_pointer = store
            .root()
            .ok_or_else(|| Error::Corrupt("the file has no root value".into()))?;
        let expected = *T::fingerprint().as_bytes();
        let found = store.root_fingerprint();
        if found != expected {
            return Err(Error::SchemaMismatch { expected, found });
        }
        let root = T::load::<_, Slotted>(&mut store, Location::new(root_pointer, 0))?;
        store.end_load();
        Ok(Kladde {
            store,
            root,
            root_pointer,
        })
    }

    /// The root value, for reading.
    ///
    /// ```
    /// use kladde::Kladde;
    ///
    /// let k = Kladde::new((1u8, true));
    /// assert_eq!(k.get().0, 1);
    /// ```
    pub fn get(&self) -> &T {
        &self.root
    }

    /// The root value's guard, through which every mutation is recorded and
    /// applied.
    ///
    /// A guard borrows the root, so nothing else can touch the structure while
    /// it lives; hold it only as long as it is needed.
    ///
    /// ```
    /// use kladde::Kladde;
    ///
    /// let mut k = Kladde::new((0u8, false));
    /// let mut guard = k.guard();
    /// let (mut n, mut flag) = guard.parts();
    /// n.set(4)?;
    /// flag.set(true)?;
    /// assert_eq!(*k.get(), (4, true));
    /// # Ok::<(), kladde::Error>(())
    /// ```
    pub fn guard(&mut self) -> RootGuard<'_, T> {
        self.root.guard(
            &self.store,
            Slotted::at(Location::new(self.root_pointer, 0)),
        )
    }

    /// Folds the journal into the file now, which also makes every mutation
    /// so far survive a power cut.
    ///
    /// Flushing happens by itself as the journal grows, so this is for
    /// choosing when: before a long idle period, say.
    ///
    /// ```
    /// use kladde::Kladde;
    ///
    /// let mut k = Kladde::new(0u32);
    /// k.guard().set(1)?;
    /// k.flush()?;
    /// assert_eq!(k.stats().flushes, 2); // the one at creation, and this one
    /// # Ok::<(), kladde::Error>(())
    /// ```
    pub fn flush(&mut self) -> Result<()> {
        self.store.flush()
    }

    /// Flushes, then truncates the file after its last live page.
    ///
    /// Free pages below that page stay in the file. Each flush consolidates a
    /// bounded amount, moving live content down, and space a flush frees is
    /// available from the next flush on; so calling [`flush`](Self::flush) a
    /// few times before closing lets more of the file be truncated. A freshly
    /// created file, for instance, needs one or two flushes before `close` to
    /// shrink to its live pages.
    ///
    /// Closing is optional: a file dropped without it, or left by a crash,
    /// opens with every mutation that returned `Ok`. See [`Kladde`] for an
    /// example.
    pub fn close(self) -> Result<()> {
        self.store.close()
    }

    /// Opens a transaction: the mutations made through it reach the journal
    /// together when it is [committed](Transaction::commit), and a crash keeps
    /// all of them or none.
    ///
    /// ```
    /// use kladde::Kladde;
    ///
    /// let mut accounts = Kladde::new((100i64, 0i64));
    /// let mut tx = accounts.transaction();
    /// let mut guard = tx.guard();
    /// let (mut from, mut to) = guard.parts();
    /// from.set(70)?;
    /// to.set(30)?;
    /// tx.commit()?;
    /// assert_eq!(*accounts.get(), (70, 30));
    /// # Ok::<(), kladde::Error>(())
    /// ```
    pub fn transaction(&mut self) -> Transaction<'_, T> {
        // A poisoned store fails every later call, the commit included.
        let _ = self.store.begin_transaction();
        Transaction {
            kladde: self,
            done: false,
        }
    }

    /// Opens a batch: the mutations made through it are appended to the
    /// journal in few, large pieces rather than one by one.
    ///
    /// A batch saves journal writes and is no transaction: a crash may keep
    /// some of its pieces and lose the rest, though never part of one
    /// mutation, nor of a transaction opened inside it with
    /// [`Batch::transaction`].
    ///
    /// ```
    /// use kladde::Kladde;
    /// use kladde_types::PersistableVec;
    ///
    /// let mut v = Kladde::new(PersistableVec::<u32>::new());
    /// let mut batch = v.batch();
    /// for i in 0..1000 {
    ///     batch.guard().push(i)?;
    /// }
    /// batch.end()?;
    /// assert_eq!(v.get().len(), 1000);
    /// # Ok::<(), kladde::Error>(())
    /// ```
    pub fn batch(&mut self) -> Batch<'_, T> {
        let _ = self.store.begin_batch();
        Batch {
            kladde: self,
            done: false,
        }
    }

    /// Counters describing the file and the work done on it since it was
    /// opened.
    ///
    /// ```
    /// use kladde::Kladde;
    ///
    /// let k = Kladde::new(0u8);
    /// assert!(k.stats().file_pages >= 3);
    /// ```
    pub fn stats(&self) -> Stats {
        self.store.stats()
    }

    /// The store backing the root, for what the root's API does not cover.
    ///
    /// ```
    /// use kladde::Kladde;
    ///
    /// let k = Kladde::new(0u8);
    /// assert!(!k.store().is_poisoned());
    /// ```
    pub fn store(&self) -> &Store {
        &self.store
    }
}

fn size(n: usize) -> Result<u32> {
    u32::try_from(n).map_err(|_| Error::OutOfBounds)
}

/// A transaction on a [`Kladde`], from [`Kladde::transaction`] or
/// [`Batch::transaction`].
///
/// Its mutations reach the journal together when it is committed. Dropping it
/// commits too, and if that fails, where no error can be returned, the store
/// is poisoned. If it is dropped while a panic unwinds, its mutations are
/// discarded and the store is poisoned instead: committing would persist a
/// half-built state, and the in-memory values already hold the mutations the
/// file will not. Reopening the file then gives the state before the
/// transaction. There is no cancelling a transaction for the same reason.
///
/// See [`Kladde::transaction`] for an example.
pub struct Transaction<'k, T: Persistable + 'static> {
    kladde: &'k mut Kladde<T>,
    done: bool,
}

impl<T: Persistable + 'static> Transaction<'_, T> {
    /// The root value's guard; mutations through it belong to the
    /// transaction. See [`Kladde::transaction`] for an example.
    pub fn guard(&mut self) -> RootGuard<'_, T> {
        self.kladde.guard()
    }

    /// The root value, for reading.
    ///
    /// ```
    /// use kladde::Kladde;
    ///
    /// let mut k = Kladde::new(1u8);
    /// let tx = k.transaction();
    /// assert_eq!(*tx.get(), 1);
    /// tx.commit()?;
    /// # Ok::<(), kladde::Error>(())
    /// ```
    pub fn get(&self) -> &T {
        self.kladde.get()
    }

    /// Ends the transaction, appending its mutations to the journal as one.
    /// See [`Kladde::transaction`] for an example.
    pub fn commit(mut self) -> Result<()> {
        self.done = true;
        self.kladde.store.end_transaction()
    }
}

impl<T: Persistable + 'static> Drop for Transaction<'_, T> {
    fn drop(&mut self) {
        if self.done {
            return;
        }
        if std::thread::panicking() {
            self.kladde.store.abandon_transaction();
        } else if self.kladde.store.end_transaction().is_err() {
            self.kladde.store.poison();
        }
    }
}

/// A batch on a [`Kladde`], from [`Kladde::batch`].
///
/// Dropping it ends it, even while a panic unwinds: every mutation inside was
/// complete, so appending them loses nothing. If ending fails there, where no
/// error can be returned, the store is poisoned.
///
/// See [`Kladde::batch`] for an example.
pub struct Batch<'k, T: Persistable + 'static> {
    kladde: &'k mut Kladde<T>,
    done: bool,
}

impl<T: Persistable + 'static> Batch<'_, T> {
    /// The root value's guard; mutations through it belong to the batch. See
    /// [`Kladde::batch`] for an example.
    pub fn guard(&mut self) -> RootGuard<'_, T> {
        self.kladde.guard()
    }

    /// The root value, for reading.
    ///
    /// ```
    /// use kladde::Kladde;
    ///
    /// let mut k = Kladde::new(1u8);
    /// let batch = k.batch();
    /// assert_eq!(*batch.get(), 1);
    /// batch.end()?;
    /// # Ok::<(), kladde::Error>(())
    /// ```
    pub fn get(&self) -> &T {
        self.kladde.get()
    }

    /// Opens a transaction inside the batch: its mutations are appended
    /// together, as one piece of the batch.
    ///
    /// ```
    /// use kladde::Kladde;
    ///
    /// let mut pair = Kladde::new((0u8, 0u8));
    /// let mut batch = pair.batch();
    /// let mut tx = batch.transaction();
    /// let mut guard = tx.guard();
    /// let (mut a, mut b) = guard.parts();
    /// a.set(1)?;
    /// b.set(2)?;
    /// tx.commit()?;
    /// batch.end()?;
    /// assert_eq!(*pair.get(), (1, 2));
    /// # Ok::<(), kladde::Error>(())
    /// ```
    pub fn transaction(&mut self) -> Transaction<'_, T> {
        self.kladde.transaction()
    }

    /// Ends the batch, appending what it held back. See [`Kladde::batch`] for
    /// an example.
    pub fn end(mut self) -> Result<()> {
        self.done = true;
        self.kladde.store.end_batch()
    }
}

impl<T: Persistable + 'static> Drop for Batch<'_, T> {
    fn drop(&mut self) {
        if !self.done && self.kladde.store.end_batch().is_err() {
            self.kladde.store.poison();
        }
    }
}

#[cfg(test)]
mod tests {
    // Deliberately through the facade, exactly as an application writes it:
    // if a name an impl needs stops being re-exported, this stops building.
    use super::*;

    /// A `u32` that keeps its four bytes in a packed place too.
    struct Counter(u32);

    impl<P: PointerRepr> Persistable<P> for Counter {
        const SLOTTED_SIZE: Option<usize> = Some(4);
        const PACKED_SIZE: Option<usize> = Some(4);

        type Guard<'s, B: WriteBackend<Pointer = P>, E: Encoding>
            = CounterGuard<'s, B, E>
        where
            Self: 's,
            B: 's;

        fn guard<'s, B: WriteBackend<Pointer = P>, E: Encoding>(
            &'s mut self,
            backend: &'s B,
            place: Place<'s, B, E>,
        ) -> Self::Guard<'s, B, E> {
            CounterGuard {
                inner: self,
                backend,
                place,
            }
        }

        fn encoded_size<E: Encoding>(&self) -> usize {
            4
        }

        fn encode<E: Encoding>(&self, out: &mut Vec<u8>) {
            out.extend_from_slice(&self.0.to_le_bytes());
        }

        fn decode<B: ReadBackend<Pointer = P>, E: Encoding>(
            _backend: &mut B,
            input: &mut Input<'_>,
        ) -> Result<Self> {
            Ok(Counter(u32::from_le_bytes(input.array()?)))
        }

        fn describe_local(_builder: &mut SchemaBuilder) -> TypeDescriptor {
            TypeDescriptor::Primitive(Primitive::U32)
        }
    }

    struct CounterGuard<'s, B: WriteBackend, E: Encoding> {
        inner: &'s mut Counter,
        backend: &'s B,
        place: Place<'s, B, E>,
    }

    impl<'s, B: WriteBackend, E: Encoding> CounterGuard<'s, B, E> {
        fn set(&mut self, value: u32) -> Result<()> {
            let at = self.place.location();
            self.backend
                .write(at.anchor, at.offset, &value.to_le_bytes())?;
            self.inner.0 = value;
            Ok(())
        }
    }

    impl<'s, B: WriteBackend, E: Encoding> Guard for CounterGuard<'s, B, E> {
        type Persistable = Counter;
        type Backend = B;

        fn as_persistable(&self) -> &Counter {
            self.inner
        }
        fn as_persistable_mut(&mut self) -> &mut Counter {
            self.inner
        }
        fn backend(&self) -> &B {
            self.backend
        }
    }

    fn reopen<T: Persistable + 'static>(k: &Kladde<T>, storage: &MemoryStorage) -> Kladde<T> {
        let _ = k;
        let image = MemoryStorage::from_image(storage.image());
        Kladde::open_in(Box::new(image), Options::default()).unwrap()
    }

    #[test]
    fn a_mutation_survives_without_a_flush() {
        let storage = MemoryStorage::new();
        let mut k =
            Kladde::create_in(Box::new(storage.clone()), Counter(0), Options::default()).unwrap();
        k.guard().set(42).unwrap();
        assert_eq!(k.get().0, 42);
        assert_eq!(reopen(&k, &storage).get().0, 42);
    }

    #[test]
    fn a_panic_inside_a_transaction_discards_it_and_poisons() {
        let storage = MemoryStorage::new();
        let mut k =
            Kladde::create_in(Box::new(storage.clone()), Counter(1), Options::default()).unwrap();
        let unwound = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let mut tx = k.transaction();
            tx.guard().set(2).unwrap();
            panic!("mid-transaction");
        }));
        assert!(unwound.is_err());
        assert!(k.store().is_poisoned());
        assert!(matches!(k.guard().set(3), Err(Error::Poisoned)));
        assert_eq!(reopen(&k, &storage).get().0, 1);
    }

    #[test]
    fn a_panic_inside_a_batch_keeps_what_it_did() {
        let storage = MemoryStorage::new();
        let mut k =
            Kladde::create_in(Box::new(storage.clone()), Counter(1), Options::default()).unwrap();
        let unwound = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            let mut batch = k.batch();
            batch.guard().set(2).unwrap();
            panic!("mid-batch");
        }));
        assert!(unwound.is_err());
        assert!(!k.store().is_poisoned());
        assert_eq!(reopen(&k, &storage).get().0, 2);
    }

    #[test]
    fn opening_with_another_root_type_fails_closed() {
        let storage = MemoryStorage::new();
        drop(Kladde::create_in(Box::new(storage.clone()), Counter(1), Options::default()).unwrap());
        let wrong = Kladde::<(u8, u8, u8, u8)>::open_in(
            Box::new(MemoryStorage::from_image(storage.image())),
            Options::default(),
        );
        assert!(matches!(wrong, Err(Error::SchemaMismatch { .. })));
    }
}
